# Generated by Django 3.2.5 on 2021-07-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210727_0656'),
        ('users', '0003_alter_user_password'),
    ]

    operations = [
    ]
